project_name: circleci-cli

archive:
  format_overrides:
    - goos: windows
      format: zip

builds:
  - binary: circleci
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
