version: 2

workflows:
  version: 2
  ci:
    jobs:
      - test
      - coverage
      - lint
      - deploy:
          requires:
            - test
            - coverage
            - lint
          filters:
            branches:
              only: master

jobs:
  test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/circleci/circleci-cli
    steps:
      - checkout
      - run: make test
  coverage:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/circleci/circleci-cli
    steps:
      - checkout
      - run: make cover
      - store_artifacts:
          path: ./coverage.txt
          destination: coverage.txt
      - run:
          name: Upload code coverage report to codecov.io
          command: |
            curl -ivX POST -H 'Accept: text/plain' \
            --data-binary @coverage.txt \
            "https://codecov.io/upload/v2\
            ?service=circleci\
            &token=$CODECOV_TOKEN\
            &commit=$CIRCLE_SHA1\
            &branch=$CIRCLE_BRANCH\
            &build=$CIRCLE_BUILD_NUM\
            &job=$CIRCLE_NODE_INDEX\
            &build_url=$CIRCLE_BUILD_URL\
            &slug=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME\
            &pr=$CIRCLE_PR_NUMBER"
  lint:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/circleci/circleci-cli
    steps:
      - checkout
      - restore_cache:
          keys: [v1-gometalinter-]
      - run:
          name: Install
          command: |
            [[ -e /go/bin/gometalinter ]] && exit
            go get -u github.com/alecthomas/gometalinter
            gometalinter --install
      - run: make lint
      - save_cache:
          key: v1-gometalinter-{{ checksum "/go/bin/gometalinter" }}
          paths: [/go/bin/*]

  deploy:
    docker:
      - image: circleci/golang:1.10
    environment:
      GORELEASER_URL:  https://github.com/goreleaser/goreleaser/releases/download/v0.77.1/goreleaser_amd64.deb

    working_directory: /go/src/github.com/circleci/circleci-cli
    steps:
      - checkout
      - restore_cache:
          keys: [v1-goreleaser-]
      - run:
          name: Install GoReleaser
          command: |
            [[ -e goreleaser ]] && exit
            curl --silent --location --fail --retry 3 $GORELEASER_URL > /tmp/goreleaser_amd64.deb
            sudo apt install /tmp/goreleaser_amd64.deb
      - run:
          name: Tag Repo
          command: |
            git config --global user.email "marc@circleci.com"
            git config --global user.name "Marc O'Morain"
            git tag -a      "v0.1.$CIRCLE_BUILD_NUM" -m "Release v0.1.$CIRCLE_BUILD_NUM"
            git push origin "v0.1.$CIRCLE_BUILD_NUM"
      - run:
          name: Release
          command: goreleaser
      - save_cache:
          key: v1-goreleaser-{{ checksum "/usr/local/bin/goreleaser" }}
          paths: [/usr/local/bin/goreleaser]
